webapp/WebApplication1/Controllers/KontaktController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ClassLibrary1.Models;
using ClassLibrary1.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using WebApplication1.Helper;

namespace WebApplication1.Controllers
{
    



    public class KontaktController : Controller
    {

        private mojDbContext db;
        private IConfiguration Configuration;

        public KontaktController(mojDbContext c, IConfiguration _config)
        {
            db = c;
            Configuration = _config;
        }


        public IActionResult Email()
        {
            return View();
        }
       
        public IActionResult SlanjeMaila(EmailVM model)
        {
            

            if (ModelState.IsValid)
            {
                Nullable<int> userID=0;

                if (Autenfikacija.GetLogiraniKorisnik(HttpContext) != null)
                    userID = Autenfikacija.GetLogiraniKorisnik(HttpContext).UserID;
                else
                    userID = null;
                

                
                EmailPostavka.SendEmail(Configuration, model.Ime, model.EmailAdresa, "Restoran public mail", model.Sadrzaj);
                TempData["poslanEmail"]="Email uspješno poslan";

                Email n = new Email
                {
                    Sadrzaj = model.Sadrzaj,
                    EmailAdresa = model.EmailAdresa,
                    VrijemeSlanja = DateTime.Now,
                    UserID = userID

                };

                db.Email.Add(n);
                db.SaveChanges();
            }
            

            return RedirectToAction("Email");
        }
    }
}

webapp/WebApplication1/Views/Kontakt/Email.cshtml
@using ClassLibrary1.ViewModels;
@using ClassLibrary1.Models;
@using WebApplication1.Helper

@model ClassLibrary1.ViewModels.EmailVM

@{ 

    
    User aktivan = Autenfikacija.GetLogiraniKorisnik(Context);
    var tekst= TempData["poslanEmail"];

}

    <div class="container">
        <div class="row">
            @{
                if (tekst != null)
                {
                    <div class="alert alert-success col-md-12 " data-alert="alert">
                        <a class="close" data-dismiss="alert">&times;</a>
                        <p class="text-center text-success">@tekst</p>
                    </div>
                }
            }

        </div>
        <div class="row">

            <div class="col-md-12 text-center mb-5 ftco-animate">
                <h2 class="display-4">Kontaktirajte nas</h2>

            </div>
            
            <div class="col-md mb-5 ftco-animate">
                <form asp-controller="Kontakt" asp-action="SlanjeMaila" method="post">
                   
                    <div class="form-group">
                        <label asp-for="Ime" class="sr-only">Ime</label>
                        <input type="text" class="form-control" asp-for="Ime" placeholder="Unesite vaše ime">
                        @*<span asp-validation-for="Ime" class="text-danger"></span>*@
                    </div>
                    <div class="form-group">
                        <label asp-for="EmailAdresa" class="sr-only">Email</label>
                        <input type="text" class="form-control" asp-for="EmailAdresa" placeholder="Unesite vaš email">
                        @*<span asp-validation-for="EmailAdresa" class="text-danger"></span>*@
                    </div>
                    <div class="form-group">
                        <label asp-for="Sadrzaj" class="sr-only">Sadrzaj</label>
                        <textarea asp-for="Sadrzaj" cols="30" rows="10" class="form-control" placeholder="Unesite vašu poruku"></textarea>
                        @*<span asp-validation-for="Sadrzaj" class="text-danger"></span>*@
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-primary btn-lg" value="Pošalji email">
                    </div>
                </form>
            </div>

        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/js/Validacija/mail.js"></script>