webapp/WebApplication1/Controllers/JelovnikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ClassLibrary1.ViewModels;
using ClassLibrary1.Models;
using WebApplication1.Models;
using WebApplication1.Helper;

namespace WebApplication1.Controllers
{
    public class JelovnikController : Controller
    {
        private mojDbContext db;

        public JelovnikController(mojDbContext c)
        {
            db = c;
        }
        public IActionResult Proizvodi()
        {
            //mojDbContext db = new mojDbContext();

            List<ProizvodJelovnikVM> proizvodiDorucak = db.Proizvod
                .Select(p => new ProizvodJelovnikVM
                {
                    ProizvodID = p.ProizvodID,
                    nazivProizvoda = p.Naziv,
                    opisProizvoda = p.Opis,
                    cijenaProizvoda = p.Cijena,
                    nazivSlike = p.Slika.lokacijaSlike,
                    tipProizvoda = p.TipProizvoda.Naziv


                }).Where(p => p.tipProizvoda == "dorucak").ToList();


            List<ProizvodJelovnikVM> proizvodiRucak = db.Proizvod
                .Select(p => new ProizvodJelovnikVM
                {
                    ProizvodID = p.ProizvodID,
                    nazivProizvoda = p.Naziv,
                    opisProizvoda = p.Opis,
                    cijenaProizvoda = p.Cijena,
                    nazivSlike = p.Slika.lokacijaSlike,
                    tipProizvoda = p.TipProizvoda.Naziv


                }).Where(p => p.tipProizvoda == "rucak").ToList();

            List<ProizvodJelovnikVM> proizvodiVecera = db.Proizvod
                .Select(p => new ProizvodJelovnikVM
                {
                    ProizvodID = p.ProizvodID,
                    nazivProizvoda = p.Naziv,
                    opisProizvoda = p.Opis,
                    cijenaProizvoda = p.Cijena,
                    nazivSlike = p.Slika.lokacijaSlike,
                    tipProizvoda = p.TipProizvoda.Naziv


                }).Where(p => p.tipProizvoda == "vecera").ToList();

           // db.Dispose();

            ViewData["proizvodiDorucak"] = proizvodiDorucak;
            ViewData["proizvodiRucak"] = proizvodiRucak;
            ViewData["proizvodiVecera"] = proizvodiVecera;


            return View();
        }
        public IActionResult Dodaj()
        {

            var model = new DodajJelovnik
            {


            };
            return View();

        }
       
        public IActionResult Spasi(DodajJelovnik model)
        {
            int last_id = db.Rezervacija.Count();

            Proizvod proizvod = new Proizvod();
            proizvod.ProizvodID = last_id+1;
            proizvod.Naziv = model.Naziv;
            proizvod.Opis = model.Opis;
            proizvod.Cijena = model.Cijena;
            proizvod.TipProizvodaID = model.TipProizvodaId;
            proizvod.UserID = Autenfikacija.GetLogiraniKorisnik(HttpContext).UserID;

            db.Proizvod.Add(proizvod);
            db.SaveChanges();
            return RedirectToAction("Pregled");
        }

       

        public IActionResult Uredi(int id)
        {
            var model = db.Proizvod.Where(i => i.ProizvodID == id).FirstOrDefault();
            return View(model);
        }
       
        public IActionResult SpasiUredi(Proizvod mod)
        {
            var model = db.Proizvod.Where(i => i.ProizvodID == mod.ProizvodID).FirstOrDefault();
            db.Remove(model);
            db.Add(mod);
            db.SaveChanges();
            return RedirectToAction("Pregled");
        }
        public IActionResult  Izbrisi(int id)
        {
            var model = db.Proizvod.Where(i => i.ProizvodID == id).FirstOrDefault();
            db.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Pregled");

        }
        public IActionResult Pregled(string q = "")
        {
            JelovnikPregled model = new JelovnikPregled();
            model.Listt = new List<ProizvodJelovnikVM>();

            List<Proizvod> list = db.Proizvod.ToList();
            foreach(var item in list)
            {
                ProizvodJelovnikVM vm = new ProizvodJelovnikVM();
                vm.nazivProizvoda = item.Naziv;
                vm.opisProizvoda = item.Opis;
                vm.cijenaProizvoda = item.Cijena;
              //  vm.tipProizvoda = item.TipProizvoda.TipProizvodaID.ToString();
                vm.ProizvodID = item.ProizvodID;
                model.Listt.Add(vm);
            }

            if (!string.IsNullOrEmpty(q))
            {
                var lista = model.Listt.Where(x => x.nazivProizvoda.ToLower().Contains(q.ToLower())).ToList();
                model.Listt = lista;
            }

            return View(model);
        }
    }
}

webapp/WebApplication1/Views/Jelovnik/Dodaj.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@using ClassLibrary1.ViewModels;
@using ClassLibrary1.Models;

@model WebApplication1.Models.DodajJelovnik
@using WebApplication1.Helper
@{
    User aktivan = Autenfikacija.GetLogiraniKorisnik(Context); }

<div> Dodaj Jelovnik</div>

<form id="jelovnikForm" asp-controller="Jelovnik" asp-action="Spasi" method="post">

    <div class="row">
        <div class="col-md-12 form-group">
            <label asp-for="Naziv">Naziv jela</label>
            <input type="text" class="form-control" asp-for="Naziv">
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 form-group">
            <label asp-for="Opis">Opis jela</label>
            <input type="text" class="form-control" asp-for="Opis">
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 form-group">
            <label asp-for="Cijena">Cijena </label>
            <input type="number" class="form-control" asp-for="Cijena">
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 form-group">
            <label asp-for="TipProizvodaId">Tip proizvoda(dorucak-1,rucak-2,vecera-3)</label>
            <input type="number" class="form-control" asp-for="TipProizvodaId">
        </div>
    </div>


    <div class="row">
        <div class="col-md-12 form-group">
            <input type="submit" class="btn btn-primary btn-lg btn-block" value="Spasi" data-save="modal">
        </div>
    </div>

</form>

webapp/WebApplication1/Views/Jelovnik/Pregled.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ClassLibrary1.ViewModels.JelovnikPregled

    <form asp-controller="Jelovnik" asp-action="Pregled">
        <p>
            Pretražite jela: <input type="text" name="q" />
            <input type="submit" value="Filter" />
        </p>
    </form>

    <table class="table">
        <thead>
            <tr>
                <th>Naziv</th>
                <th>Opis</th>
                <th>Cijena</th>
                <th>Akcija</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var row in Model.Listt)
            {
                <tr>
                    <td>@row.nazivProizvoda</td>
                    <td>@row.opisProizvoda</td>
                    <td>@row.cijenaProizvoda</td>

                    <td> <a asp-controller="Jelovnik" asp-action="Dodaj" asp-route-id="null">Dodaj</a></td>
                    <td> <a asp-controller="Jelovnik" asp-action="Uredi" asp-route-id="@row.ProizvodID">Uredi</a></td>
                    <td> <a asp-controller="Jelovnik" asp-action="Izbrisi" asp-route-id="@row.ProizvodID">Izbrisi</a></td>
                    <td>
                        <a asp-controller="ReportController1" asp-action="Index">Izvjestaj pdf</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

webapp/WebApplication1/Views/Jelovnik/Proizvodi.cshtml
@using ClassLibrary1.ViewModels;

@{
    Layout = "_Layout";
    var proizvodDorucak = (List<ProizvodJelovnikVM>)ViewData["proizvodiDorucak"];
    var proizvodRucak = (List<ProizvodJelovnikVM>)ViewData["proizvodiRucak"];
    var proizvodVecera= (List<ProizvodJelovnikVM>)ViewData["proizvodiVecera"];
}




<!DOCTYPE html>
<html lang="en">
<head>

</head>
<body data-spy="scroll" data-target="#ftco-navbar" data-offset="200">



    <section class="ftco-section" id="section-menu">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center mb-5 ftco-animate">
                    <h2 class="display-4">Današnji meni</h2>
                   
                </div>

                <div class="col-md-12 text-center">

                    <ul class="nav ftco-tab-nav nav-pills mb-5" id="pills-tab" role="tablist">
                        <li class="nav-item ftco-animate">
                            <a class="nav-link active" id="pills-breakfast-tab" data-toggle="pill" href="#pills-breakfast" role="tab" aria-controls="pills-breakfast" aria-selected="true">Breakfast</a>
                        </li>
                        <li class="nav-item ftco-animate">
                            <a class="nav-link" id="pills-lunch-tab" data-toggle="pill" href="#pills-lunch" role="tab" aria-controls="pills-lunch" aria-selected="false">Lunch</a>
                        </li>
                        <li class="nav-item ftco-animate">
                            <a class="nav-link" id="pills-dinner-tab" data-toggle="pill" href="#pills-dinner" role="tab" aria-controls="pills-dinner" aria-selected="false">Dinner</a>
                        </li>
                    </ul>

                    <div class="tab-content text-left">
                        <div class="tab-pane fade show active" id="pills-breakfast" role="tabpanel" aria-labelledby="pills-breakfast-tab">
                            <div class="row">


                                @foreach (var pr in proizvodDorucak)
                                {
                                    <div class="col-md-6 ftco-animate">
                                        <div class="media menu-item">
                                            <img class="mr-3" src="/images/@pr.nazivSlike" class="img-fluid" alt="Free Template by Free-Template.co">
                                            <div class="media-body">
                                                <h5 class="mt-0">@pr.nazivProizvoda</h5>
                                                <p>@pr.opisProizvoda</p>
                                                <h6 class="text-primary menu-price">@pr.cijenaProizvoda KM</h6>
                                            </div>
                                        </div>



                                    </div>
                                }



                               
                            </div>
                        </div>
                        <div class="tab-pane fade" id="pills-lunch" role="tabpanel" aria-labelledby="pills-lunch-tab">
                            <div class="row">

                                @foreach (var proizvod in proizvodRucak)
                                {
                                    <div class="col-md-6 ftco-animate">

                                        <div class="media menu-item">
                                            <img class="mr-3" src="/images/@proizvod.nazivSlike" class="img-fluid" alt="Free Template by Free-Template.co">
                                            <div class="media-body">
                                                <h5 class="mt-0">@proizvod.nazivProizvoda</h5>
                                                <p>@proizvod.opisProizvoda</p>
                                                <h6 class="text-primary menu-price">@proizvod.cijenaProizvoda KM</h6>
                                            </div>
                                        </div>



                                    </div>
                                }



                            </div>
                        </div>
                        <div class="tab-pane fade" id="pills-dinner" role="tabpanel" aria-labelledby="pills-dinner-tab">
                            <div class="row">
                                @foreach (var proizvod in proizvodVecera)
                                {
                                    <div class="col-md-6 ftco-animate">

                                        <div class="media menu-item">
                                            <img class="mr-3" src="/images/@proizvod.nazivSlike" class="img-fluid" alt="Free Template by Free-Template.co">
                                            <div class="media-body">
                                                <h5 class="mt-0">@proizvod.nazivProizvoda</h5>
                                                <p>@proizvod.opisProizvoda</p>
                                                <h6 class="text-primary menu-price">@proizvod.cijenaProizvoda KM</h6>
                                            </div>
                                        </div>



                                    </div>
                                }

                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>




</body>
</html>

webapp/WebApplication1/Views/Jelovnik/Uredi.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ClassLibrary1.Models.Proizvod

<div> Uredi Jelovnik</div>
<form id="jelovnikFormm" asp-controller="Jelovnik" asp-action="SpasiUredi" method="post">
    @Html.HiddenFor(model => model.ProizvodID);
    @Html.AntiForgeryToken()
    <div class="editor-label">
        <div class="col-md-12 form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="editor-label">
        <div class="col-md-12 form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <div class="editor-label">
        <div class="col-md-12 form-group">
            @Html.LabelFor(model => model.Cijena, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Cijena, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <div class="editor-label">
        <div class="col-md-12 form-group">
            @Html.LabelFor(model => model.TipProizvodaID, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.TipProizvodaID, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 form-group">
            <input type="submit" class="btn btn-primary btn-lg btn-block" value="Spasi" data-save="modal">
        </div>
    </div>

</form>