webapp/WebApplication1/Controllers/ObavijestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ClassLibrary1.Models;
using ClassLibrary1.ViewModels;
using WebApplication1.Helper;
using WebApplication1.Hubs;
using Microsoft.AspNetCore.SignalR;
using WebApplication1.Models;


namespace WebApplication1.Controllers
{
    public class ObavijestController : Controller
    {
        private mojDbContext db;

        public ObavijestController(mojDbContext c)
        {
            db = c;
        }
        public IActionResult Novosti()
        {



            List<ObavijestVM> obavijest = db.Obavijest
                .Select(p => new ObavijestVM
                {
                    ObavijestID = p.ObavijestID,
                    NazivObavijesti = p.Naslov,
                    SadrZajObavijesti = p.Sadrzaj,
                    nazivSlike = p.Slika.lokacijaSlike


                }).OrderByDescending(p => p.ObavijestID).ToList();

            ViewData["obavijestiKljuc"] = obavijest;



            return View();
        }

        public int brojacObavijesti()
        {
            int br = 0;
            br = db.Obavijest.Select(o => o.ObavijestID).Count();
            return br;
        }

        



        public IActionResult Dodaj()
        {

            var model = new DodajRezervaciju
            {


            };
            return View();

        }
       

        public IActionResult Spasi(DodajObavijest model)
        {
            int last_id = db.Rezervacija.Count();  
            Obavijest obavijest = new Obavijest();
            obavijest.ObavijestID = last_id + 1;
            obavijest.Naslov = model.Naslov;
            obavijest.Sadrzaj = model.Sadrzaj;
            obavijest.VrijemeObjave = model.Vrijeme;
            obavijest.UserID = Autenfikacija.GetLogiraniKorisnik(HttpContext).UserID;
            db.Obavijest.Add(obavijest);    
            db.SaveChanges();
            return RedirectToAction("Pregled");

        }

        public IActionResult Uredi(int id)
        {
            var model = db.Obavijest.Where(i => i.ObavijestID == id).FirstOrDefault();
            return View(model);
        }

        public IActionResult SpasiUredi(Obavijest mod)
        {
            var model = db.Obavijest.Where(i => i.ObavijestID == mod.ObavijestID).FirstOrDefault();
            db.Remove(model);
            db.Add(mod);
            db.SaveChanges();

            return RedirectToAction("Pregled");

        }
        public IActionResult Izbrisi(int id)
        {
            var model = db.Obavijest.Where(i => i.ObavijestID == id).FirstOrDefault();
            db.Remove(model);
            db.SaveChanges();

            return RedirectToAction("Pregled");

        }
        public IActionResult Pregled(string q = "")
        {
            ObavijestPregled model = new ObavijestPregled();
            model.Listt = new List<ObavijestVM>();
            List<Obavijest> list = db.Obavijest.ToList();
            foreach (var item in list)
            {
                ObavijestVM vm = new ObavijestVM();
                vm.SadrZajObavijesti = item.Sadrzaj;
                vm.NazivObavijesti = item.Naslov;
                vm.datum = item.VrijemeObjave;
                vm.ObavijestID = item.ObavijestID;
                model.Listt.Add(vm);
            }

            if (!string.IsNullOrEmpty(q))
            {
                var lista = model.Listt.Where(x => x.NazivObavijesti.ToLower().Contains(q.ToLower())).ToList();
                model.Listt = lista;
            }

            return View(model);
        }

    }
}

webapp/WebApplication1/Views/Obavijest/Dodaj.cshtml
@using ClassLibrary1.ViewModels;
@using ClassLibrary1.Models;
@using WebApplication1.Helper
@{
    Layout = "_Layout";
    var obavijesti = (List<ObavijestDodaj>)ViewData["obavijestiKljuc"];
    User aktivan = Autenfikacija.GetLogiraniKorisnik(Context);
}

@model WebApplication1.Models.DodajObavijest

<div> Dodaj obavijest</div>

<form id="obavjestForm" asp-controller="Obavijest" asp-action="Spasi" method="post">
 
    <div class="row">
        <div class="col-md-12 form-group">
            <label asp-for="Sadrzaj">Sadrzaj</label>
            <input type="text" class="form-control" asp-for="Sadrzaj">
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 form-group">
            <label asp-for="Naslov">Naslov</label>
            <input type="text" class="form-control" asp-for="Naslov">
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 form-group">
            <label asp-for="Vrijeme">Vrijeme</label>
            <input type="date" class="form-control" asp-for="Vrijeme">
        </div>
    </div>


    <div class="row">
        <div class="col-md-12 form-group">
            <input type="submit" class="btn btn-primary btn-lg btn-block" value="Spasi" data-save="modal">
        </div>
    </div>

</form>

webapp/WebApplication1/Views/Obavijest/Novosti.cshtml
@using ClassLibrary1.ViewModels;

@{
    Layout = "_Layout";
    var obavijesti= (List<ObavijestVM>)ViewData["obavijestiKljuc"];
}



<!DOCTYPE html>
<html lang="en">
<head>

</head>
<body data-spy="scroll" data-target="#ftco-navbar" data-offset="200">




    <div class="container">

        <div class="row">
            <div class="col-md-12 text-center mb-5 ftco-animate">
                <h2 class="display-4">Nosti i događaji</h2>
                
            </div>
            @foreach (var obavijest in obavijesti)
            {
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="media d-block mb-4 text-center ftco-media ftco-animate">
                        <img src="/images/@obavijest.nazivSlike" alt="Free Template by Free-Template.co" class="img-fluid">
                        <div class="media-body p-md-5 p-4">
                            <h5 class="mt-0 h4">@obavijest.NazivObavijesti</h5>
                            <p class="mb-4">@obavijest.SadrZajObavijesti</p>

                            
                        </div>
                    </div>
                </div>
            }


        </div>
    </div>




</body>
</html>

webapp/WebApplication1/Views/Obavijest/Pregled.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ClassLibrary1.ViewModels.ObavijestPregled

    <form asp-controller="Obavijest" asp-action="Pregled">
        <p>
            Pretražite obavijesti: <input type="text" name="q" />
            <input type="submit" value="Filter" />
        </p>
    </form>

<table class="table">
    <thead>
        <tr>
            <th>Naslov</th>
            <th>Sadrzaj</th>
            <th>Datum</th>
            <th>Akcija</th>

        </tr>
    </thead>
    <tbody>
        @foreach(var row in Model.Listt)
            {
        <tr>
            <td>@row.NazivObavijesti</td>
            <td>@row.SadrZajObavijesti</td>
            <td>@row.datum</td>
            <td> <a asp-controller="Obavijest" asp-action="Dodaj" asp-route-id="null">Dodaj</a></td>
            <td> <a asp-controller="Obavijest" asp-action="Uredi" asp-route-id="@row.ObavijestID">Uredi</a></td>
            <td> <a asp-controller="Obavijest" asp-action="Izbrisi" asp-route-id="@row.ObavijestID">Izbrisi</a></td>
        </tr>
            }
    </tbody>
</table>

webapp/WebApplication1/Views/Obavijest/Uredi.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model ClassLibrary1.Models.Obavijest
  



    <div> Uredi obavijest</div>
    <form id="obavjestFormm" asp-controller="Obavijest" asp-action="SpasiUredi" method="post">
        @Html.HiddenFor(model => model.ObavijestID);
        @Html.AntiForgeryToken()
        <div class="editor-label">
            <div class="col-md-12 form-group">
                @Html.LabelFor(model => model.Sadrzaj, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Sadrzaj, new { htmlAttributes = new { @class = "form-control" } })        
            </div>
        </div>

        <div class="editor-label">
            <div class="col-md-12 form-group">
                @Html.LabelFor(model => model.Naslov, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.Naslov, new { htmlAttributes = new { @class = "form-control" } })            
            </div>
        </div>
        <div class="editor-label">
            <div class="col-md-12 form-group">
                @Html.LabelFor(model => model.VrijemeObjave, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.VrijemeObjave, new { htmlAttributes = new { @class = "form-control" } })              
            </div>
        </div>

        


        <div class="row">
            <div class="col-md-12 form-group">
                <input type="submit" class="btn btn-primary btn-lg btn-block" value="Spasi" data-save="modal">
            </div>
        </div>

    </form>