webapp/WebApplication1/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ClassLibrary1.Models;
using ClassLibrary1.ViewModels;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using WebApplication1.Helper;
using WebApplication1.Hubs;

namespace WebApplication1.Controllers
{
    public class ChatController : Controller
    {

        private mojDbContext db;
        private readonly IHubContext<ChatHub> _hubContext;
        


        public ChatController(mojDbContext context, IHubContext<ChatHub> hubContext)
        {
            db = context;
            _hubContext = hubContext;
            
        }
        //[Autorizacija(true, true)]
        //public IActionResult Index()
        //{

        //    ListaPorukaVM model = new ListaPorukaVM();
        //    var user = Autenfikacija.GetLogiraniKorisnik(HttpContext);
        //    if (user.UlogaID == 2)
        //    {
              
        //        model.ListaPoruka = db.Poruka
        //      .Select(r => new ListaPorukaVM.Row
        //      {

        //          Sadrzaj = r.Sadrzaj,
        //          User = r.User.ime,
        //          VrijemePoruke = r.VrijemeSlanja.ToShortTimeString(),
        //          DatumPoruke = r.VrijemeSlanja.ToShortDateString(),
        //          VrijemeDatumPoruka = r.VrijemeSlanja,
        //          ChatID= r.Chat.ChatID
        //      }).Where((n => n.VrijemeDatumPoruka >= (DateTime.Now.AddDays(-1)))).Where((e => e.ChatID == user.UserID)).ToList();


               

        //    }


        //    return View(model);


        //}

        public IActionResult SubmitFormPartial()
        {
            var user = Autenfikacija.GetLogiraniKorisnik(HttpContext);

            if(user.UlogaID==2)
            {
                var brAktivnihDjelatnika = db.Konekcija.Where(k => k.User.UlogaID == 1).Select(k => k.Vrijednost).Count();

                if (brAktivnihDjelatnika == 0)
                    TempData["brAktivnihDjelatnika"] = "Trenutno korisnička podrška nije na mreži";
            }
            
            return PartialView();
        }

        //public IActionResult PosaljiPoruku(PorukaVM model)
        //{

        //    if (ModelState.IsValid)
        //    {
        //        var userID = Autenfikacija.GetLogiraniKorisnik(HttpContext).UserID;
        //        var user = Autenfikacija.GetLogiraniKorisnik(HttpContext);
        //        if (user.UlogaID == 2)
        //        {
        //            if (db.Chat.Find(userID) == null)
        //            {
        //                Chat ch = new Chat
        //                {
        //                    UserID = userID,
        //                    ChatID = userID,
        //                    VrijemePocetka = System.DateTime.Now
        //                };
        //                db.Chat.Add(ch);
        //                db.SaveChanges();
        //            }

        //            Poruka nova = new Poruka
        //            {

        //                VrijemeSlanja = System.DateTime.Now,

        //                UserID = userID,
        //                ChatID = userID,
        //                Sadrzaj = model.Poruka



        //            };
        //            db.Poruka.Add(nova);
        //            db.SaveChanges();


        //        }







        //        var datum = System.DateTime.Now.ToShortDateString();
        //        var vrijeme = System.DateTime.Now.ToShortTimeString();

        //        _hubContext.Clients.Group(userID.ToString()).SendAsync("PrimljenaPoruka", model.Poruka, datum, vrijeme, user.ime);


        //        ModelState.Clear();
        //    }
           
        //    return PartialView("SubmitFormPartial");
            
        //}

        
    }
}

webapp/WebApplication1/Controllers/GalerijaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ClassLibrary1.ViewModels;
using ClassLibrary1.Models;
using WebApplication1.Models;
using WebApplication1.Helper;
using System.IO;

namespace WebApplication1.Controllers
{
    public class GalerijaController : Controller
    {
        private mojDbContext db;

        public GalerijaController(mojDbContext c)
        {
            db = c;
        }
        public IActionResult Slike()
        {

           

            List<SlikaVM> slika = db.Slika
                .Select(s => new SlikaVM
                {
                   SlikaID= s.SlikaID,
                   nazivSlike= s.lokacijaSlike


                }).ToList();

            ViewData["slikaKljuc"] = slika;
            //db.Dispose();


            return View();

        }

        public IActionResult Dodaj()
        {

            var model = new DodajSliku
            {


            };
            return View();

        }
        [HttpPost]

        public IActionResult Spasi(DodajSliku model)
        {
            int last_id = db.Slika.Count();

            Slika obavijest = new Slika();
            obavijest.SlikaID = last_id + 1;
            obavijest.datumPostavljanja = model.Datum;
            obavijest.lokacijaSlike = model.Lokacija;
            //obavijest.UserID = Autenfikacija.GetLogiraniKorisnik(HttpContext).UserID;
            // obavijest.UserID = model.UserId;
             obavijest.slika = model.Slika;
           
            if (model.slikaStudentaNew != null)
            {
                string ekstenzija = Path.GetExtension(model.slikaStudentaNew.FileName);
                string contentType = model.slikaStudentaNew.ContentType;

                var filename = $"{Guid.NewGuid()}{ekstenzija}";
                string folder = "wwwroot/uploads/";
                bool exists = System.IO.Directory.Exists(folder);
                if (!exists)
                    System.IO.Directory.CreateDirectory(folder);

                model.slikaStudentaNew.CopyTo(new FileStream(folder + filename, FileMode.Create));
                obavijest.lokacijaSlike = filename;
            }
            db.Slika.Add(obavijest);
            db.SaveChanges();
            return RedirectToAction("Pregled");

        }
        public IActionResult Pregled()
        {
            SlikaPregled model = new SlikaPregled();
            model.Listt = new List<SlikaVM>();
            List<Slika> list = db.Slika.ToList();
            foreach (var item in list)
            {
                SlikaVM vm = new SlikaVM();
                vm.SlikaID = item.SlikaID;
              
                vm.Lokacija = item.lokacijaSlike;
                vm.Datum = item.datumPostavljanja;
                model.Listt.Add(vm);
            }
            return View(model);
        }
        public IActionResult Izbrisi(int id)
        {
            var model = db.Slika.Where(i => i.SlikaID == id).FirstOrDefault();
            db.Remove(model);
            db.SaveChanges();

            return RedirectToAction("Pregled");

        }
        public IActionResult Uredi(int id)
        {
            var model = db.Slika.Where(i => i.SlikaID == id).FirstOrDefault();
            return View(model);
        }
        public IActionResult SpasiUredi(Slika mod)
        {
            var model = db.Slika.Where(i => i.SlikaID == mod.SlikaID).FirstOrDefault();
            db.Remove(model);
            db.Add(mod);
            db.SaveChanges();

            return RedirectToAction("Pregled");

        }
    }
}

webapp/WebApplication1/Controllers/PodrskaController.cs
using ClassLibrary1.Models;
using ClassLibrary1.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Helper;

namespace WebApplication1.Controllers
{
    public class PodrskaController : Controller
    {
        

            private mojDbContext db;
            private IConfiguration Configuration;

            public PodrskaController(mojDbContext c, IConfiguration _config)
            {
                db = c;
                Configuration = _config;
            }


            public IActionResult Email()
            {
                return View();
            }

            public IActionResult SlanjeMaila(EmailVM model)
            {


                if (ModelState.IsValid)
                {
                    Nullable<int> userID = 0;

                    if (Autenfikacija.GetLogiraniKorisnik(HttpContext) != null)
                        userID = Autenfikacija.GetLogiraniKorisnik(HttpContext).UserID;
                    else
                        userID = null;



                EmailPostavka.SendEmail(Configuration, model.Ime, model.EmailAdresa, "Restoran public mail", model.Sadrzaj);
                    TempData["poslanEmail"] = "Email uspješno poslan";

                int last_id = db.Email.ToList().Last().EmailID;
                    Email n = new Email
                    {
                        EmailID= last_id+1,
                        Sadrzaj = model.Sadrzaj,
                        EmailAdresa = model.EmailAdresa,
                        VrijemeSlanja = DateTime.Now,
                        UserID = userID

                    };

                    db.Email.Add(n);
                    db.SaveChanges();
                }


                return RedirectToAction("Email");
            }
        }
    }

webapp/WebApplication1/Controllers/PrijavaController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ClassLibrary1.Models;
using ClassLibrary1.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebApplication1.Helper;
using WebApplication1.Hubs;
using WebApplication1.Models;
using System.Runtime;
using Xceed.Wpf.Toolkit;

namespace WebApplication1.Controllers
{
    public class PrijavaController : Controller
    {
        private mojDbContext db;

        public PrijavaController(mojDbContext c)
        {
            db = c;
        }
        public IActionResult Index()
        {
            return PartialView();
        }

        public IActionResult Prijava(PrijavaVM model)
        {


            if (ModelState.IsValid)
            {
               
                User u = db.User.SingleOrDefault(k => k.Nalog.Email == model.Email && k.Nalog.Lozinka == model.Lozinka);

                if (u == null)
                {
                    TempData["neuspjesnaprijava"] = "pogrešno ste unjeli email ili lozinku";
                    return PartialView("Index", model);

                  

                }

                Autenfikacija.SetLogiraniKorisnik(HttpContext, u);

               
               

            }
             //ako je uloga id= 1 otvori za korisnike
             //ako je uloga id 2 otvori za admina
            return PartialView("Index", model);


        }
        public IActionResult PrijavaAngular(string model)
        {


         

                User u = db.User.SingleOrDefault(k => k.Nalog.Email == "admin@hotmail.com");

                if (u == null)
                {
                    TempData["neuspjesnaprijava"] = "pogrešno ste unjeli email ili lozinku";
                    return PartialView("Index", model);



                }

                Autenfikacija.SetLogiraniKorisnik(HttpContext, u);





            //ako je uloga id= 1 otvori za korisnike
            //ako je uloga id 2 otvori za admina
            return Ok(u);


        }

        //public string? FileName { get; }
        //public class FileNotFoundException : System.IO.FileNotFoundException { };


        [HttpPost]
        public IActionResult Registracija([FromQuery] string ime ,string prezime, string username,string lozinka)
        {
            int last_nalog_id = db.Nalog.ToList().Last().NalogID + 1;
            int last_user_id = db.User.ToList().Last().UserID + 1;

            var sr = new StreamReader(Request.Body);
            //string json = await sr.ReadAsync(Request.Body.Read());
            //var model = JsonConvert.DeserializeObject<RegistracijaUser>(json);
            string adresa = "adresa";
            string mob = "06374136";
            User u = new User();
            u.ime = ime;        
            u.prezime = prezime;
            u.adresaStanovanja = adresa;
            u.brojTelefona = mob;
            u.UserID = last_user_id;
            Nalog nalog = new Nalog();
            nalog.DatumKreiranja = DateTime.Now;
            nalog.Email =username;
            nalog.Lozinka= lozinka;
            nalog.NalogID=last_nalog_id;
            db.Nalog.Add(nalog);
            db.SaveChanges();
            u.NalogID = db.Nalog.Where(x=>x.Email==nalog.Email).FirstOrDefault().NalogID;
            db.User.Add(u);
            db.SaveChanges();
            return Ok();

        }
        public IActionResult Odjava()
        {



            Autenfikacija.SetLogiraniKorisnik(HttpContext, null);
            return RedirectToAction("Index","Home");
        }

        public IActionResult Pregled()
        {
            UserPregled model = new UserPregled();
            model.Listt = new List<User>();
            List<User> list = db.User.ToList();
            foreach(var item in list)
            {
                User vm = new User();
                vm.adresaStanovanja = item.adresaStanovanja;
                vm.brojTelefona = item.brojTelefona;
                vm.ime = item.ime;
                vm.prezime = item.prezime;
                vm.UserID = item.UserID;
                vm.UlogaID = item.UlogaID; 
                vm.NalogID = item.NalogID;
                model.Listt.Add(vm);
            }
            return View(model);
        }

        public IActionResult PregledAngular()
        {
            UserPregled model = new UserPregled();
            model.Listt = new List<User>();
            List<User> list = db.User.ToList();

            return Ok(list);
        }

    }
}

webapp/WebApplication1/Views/Shared/_Layout.cshtml
@using ClassLibrary1.Models
@using WebApplication1.Helper
@using Microsoft.AspNetCore.Http;
@{ User aktivan = Autenfikacija.GetLogiraniKorisnik(Context); }

<!DOCTYPE html>
<html lang="en">


<head>
    <title>Taste - Free Bootstrap 4 Template by Free-Template.co</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Free Template by Free-Template.co" />
    <meta name="keywords" content="free bootstrap 4, free bootstrap 4 template, free website templates, free html5, free template, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="Free-Template.co" />

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700|Raleway" rel="stylesheet">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="/css/animate.css">

    <link rel="stylesheet" href="/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="/css/magnific-popup.css">

    <link rel="stylesheet" href="/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="/css/jquery.timepicker.css">



    <link rel="stylesheet" href="/css/icomoon.css">
    <link rel="stylesheet" href="/css/style.css">
    <link href="~/css/chatbox.css" rel="stylesheet" />


</head>
<body>


    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                @{ if (aktivan == null)
                    {
        <button type="button" class="navbar-brand btn btn-light" ajax-modalni="da" ajax-rezultat="PrijavaPlaceholder" ajax-url="@Url.Action("Index", "Prijava")"> Prijavi se</button> }
    else
    { @*<a asp-controller="Prijava" asp-action="Odjava" class="navbar-brand btn btn-light">@aktivan.ime</a>*@
                    <a asp-controller="Rezervacija" asp-action="ListaRezervacija" class="navbar-brand btn btn-light">@aktivan.ime</a> } }

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="oi oi-menu"></span> Menu
                </button>

                <div class="collapse navbar-collapse" id="ftco-nav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active"><a asp-controller="Home" asp-action="IndexAdmin" class="nav-link">Početna</a></li>
                        <li class="nav-item"><a asp-controller="Obavijest" asp-action="Pregled" class="nav-link">Obavijest</a></li>
                        <li class="nav-item"><a asp-controller="Jelovnik" asp-action="Pregled" class="nav-link">Jelovnik</a></li>
                        <li class="nav-item"><a asp-controller="PosebnaPonuda" asp-action="Pregled" class="nav-link">Posebna ponuda</a></li>

                        <li class="nav-item"><a asp-controller="Galerija" asp-action="Pregled" class="nav-link">Galerija</a></li>
                        <li class="nav-item"><a asp-controller="Komentar" asp-action="Lista" class="nav-link">Komentari</a></li>
                        <li class="nav-item"><a asp-controller="Poslovnicaa" asp-action="Pregled" class="nav-link">Poslovnice</a></li>
                        <li class="nav-item"><a asp-controller="Podrska" asp-action="Email" class="nav-link">Podrska</a></li>


                        @*@if (aktivan != null)
        {
            <li class="nav-item"><a asp-controller="Chat" asp-action="Index" class="nav-link">Chat</a></li>
        }*@



                    </ul>
                </div>
            </div>
        </nav>
        <div id="PrijavaPlaceholder"></div>

    </header>



    @RenderBody()




    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>

    <script src="~/js/bootstrap-datepicker.js"></script>
    <script src="~/js/jquery.timepicker.min.js"></script>



    <script src="~/js/main.js"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/js/Validacija/rezervacija.js"></script>
    <script src="~/js/Validacija/login.js"></script>
    <script src="~/images/"></script>


    @*<script src="~/SignalR/dist/browser/signalr.js"></script>*@
    @*<script src="~/js/chat.js"></script>*@
    <script src="~/js/jsFunkcije.js"></script>

    <script>

    var pSuccess = '@TempData["porukaSuccess"]';
    var pInfo = '@TempData["PorukaInfo"]';
    var pWarning = '@TempData["PorukaWarning"]';
    var pError = '@TempData["PorukaError"]';

   
    porukaSuccess(pSuccess);
    porukaInfo(pInfo);
    porukaWarning(pWarning);
    porukaError(pError);

    </script>


</body>
</html>

webapp/WebApplication1/Views/Shared/_LayoutAdmin.cshtml
@using ClassLibrary1.Models
@using WebApplication1.Helper
@using Microsoft.AspNetCore.Http;
@{

    User aktivan = Autenfikacija.GetLogiraniKorisnik(Context);

}

<!DOCTYPE html>
<html lang="en">


<head>
    <title>Taste - Free Bootstrap 4 Template by Free-Template.co</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Free Template by Free-Template.co" />
    <meta name="keywords" content="free bootstrap 4, free bootstrap 4 template, free website templates, free html5, free template, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="Free-Template.co" />

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700|Raleway" rel="stylesheet">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="/css/animate.css">

    <link rel="stylesheet" href="/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="/css/magnific-popup.css">

    <link rel="stylesheet" href="/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="/css/jquery.timepicker.css">



    <link rel="stylesheet" href="/css/icomoon.css">
    <link rel="stylesheet" href="/css/style.css">
    <link href="~/css/chatbox.css" rel="stylesheet" />


</head>
<body>


    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                @{
                    if (aktivan == null)
                    {
                        <button type="button" class="navbar-brand btn btn-light" ajax-modalni="da" ajax-rezultat="PrijavaPlaceholder" ajax-url="@Url.Action("Index", "Prijava")"> Prijavi se</button>
                    }
                    else
                    {
                        @*<a asp-controller="Prijava" asp-action="Odjava" class="navbar-brand btn btn-light">@aktivan.ime</a>*@
                        <a asp-controller="Rezervacija" asp-action="ListaRezervacija" class="navbar-brand btn btn-light">@aktivan.ime</a>
                    }
                }

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="oi oi-menu"></span> Menu
                </button>

                <div class="collapse navbar-collapse" id="ftco-nav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active"><a asp-controller="Home" asp-action="IndexAdmin" class="nav-link">Početna</a></li>
                        <li class="nav-item"><a asp-controller="Obavijest" asp-action="Pregled" class="nav-link">Obavijest</a></li>
                        <li class="nav-item"><a asp-controller="Jelovnik" asp-action="Pregled" class="nav-link">Jelovnik</a></li>
                        <li class="nav-item"><a asp-controller="PosebnaPonuda" asp-action="Pregled" class="nav-link">Posebna ponuda</a></li>

                        <li class="nav-item"><a asp-controller="Galerija" asp-action="Pregled" class="nav-link">Galerija</a></li>
                        <li class="nav-item"><a asp-controller="Komentar" asp-action="Pregled" class="nav-link">Komentari</a></li>
                        <li class="nav-item"><a asp-controller="Poslovnicaa" asp-action="Pregled" class="nav-link">Poslovnice</a></li>
                        <li class="nav-item"><a asp-controller="Podrska" asp-action="Email" class="nav-link">Podrska</a></li>


                        @*@if (aktivan != null)
        {
            <li class="nav-item"><a asp-controller="Chat" asp-action="Index" class="nav-link">Chat</a></li>
        }*@




                    </ul>
                </div>
            </div>
        </nav>
        <div id="PrijavaPlaceholder"></div>

    </header>



    @RenderBody()




    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>

    <script src="~/js/bootstrap-datepicker.js"></script>
    <script src="~/js/jquery.timepicker.min.js"></script>



    <script src="~/js/main.js"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/Validacija/rezervacija.js"></script>
    <script src="~/js/Validacija/login.js"></script>
    <script src="~/images/"></script>

    @*<script src="~/SignalR/dist/browser/signalr.js"></script>*@
    @*<script src="~/js/chat.js"></script>*@
    <script src="~/js/jsFunkcije.js"></script>

    <script>

    var pSuccess = '@TempData["porukaSuccess"]';
    var pInfo = '@TempData["PorukaInfo"]';
    var pWarning = '@TempData["PorukaWarning"]';
    var pError = '@TempData["PorukaError"]';


    porukaSuccess(pSuccess);
    porukaInfo(pInfo);
    porukaWarning(pWarning);
    porukaError(pError);

    </script>


</body>
</html>

webapp/WebApplication1/Views/Shared/_LayoutAnon.cshtml
@using ClassLibrary1.Models
@using WebApplication1.Helper
@using Microsoft.AspNetCore.Http;
@{ // Nalog aktivan = Autenfikacija.GetLogiraniKorisnik(Context);
                Layout = "_LayoutAnon"; }

<!DOCTYPE html>
<html lang="en">


<head>
    <title>Taste - Free Bootstrap 4 Template by Free-Template.co</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Free Template by Free-Template.co" />
    <meta name="keywords" content="free bootstrap 4, free bootstrap 4 template, free website templates, free html5, free template, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="Free-Template.co" />

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700|Raleway" rel="stylesheet">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="/css/animate.css">

    <link rel="stylesheet" href="/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="/css/magnific-popup.css">

    <link rel="stylesheet" href="/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="/css/jquery.timepicker.css">



    <link rel="stylesheet" href="/css/icomoon.css">
    <link rel="stylesheet" href="/css/style.css">



</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand btn btn-light" asp-controller="Home" asp-action="Index">Taste</a>
                @*<a class="navbar-brand" href="/Prijava/index" ajax-modalni="da" ajax-rezultat="PrijavaPlaceholder">Prijava</a>*@
                <button type="button" class="navbar-brand btn btn-light" ajax-modalni="da" ajax-rezultat="PrijavaPlaceholder" ajax-url="@Url.Action("Index","Prijava")"> Prijavi se</button>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="oi oi-menu"></span> Menu
                </button>

                <div class="collapse navbar-collapse" id="ftco-nav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active"><a asp-controller="Home" asp-action="Index" class="nav-link">Početna</a></li>
                        <li class="nav-item"><a asp-controller="Proizvod" asp-action="Ponuda" class="nav-link">Ponuda</a></li>
                        <li class="nav-item"><a asp-controller="Jelovnik" asp-action="Proizvodi" Class="nav-link">Meni</a></li>
                        <li class="nav-item"><a asp-controller="Obavijest" asp-action="Novosti" class="nav-link">Vijesti</a></li>
                        <li class="nav-item"><a asp-controller="Galerija" asp-action="Slike" class="nav-link">Galerija</a></li>
                        <li class="nav-item"><a asp-controller="Komentar" asp-action="Lista" class="nav-link">Komentari</a></li>
                        @*<li class="nav-item"><a asp-controller="Komentar" asp-action="Lista" class="nav-link">@aktivan.Email</a></li>*@
                        @*<li class="nav-item"><a href="#section-contact" class="nav-link">Kontakt</a></li>
                        *@
                    </ul>
                </div>
            </div>
        </nav>
        <div id="PrijavaPlaceholder"></div>
    </header>

    @RenderBody()


    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>

    <script src="~/js/bootstrap-datepicker.js"></script>
    <script src="~/js/jquery.timepicker.min.js"></script>

    <script src="~/js/jquery.animateNumber.min.js"></script>


    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>

    <script src="~/js/google-map.js"></script>

    <script src="~/js/main.js"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/jsFunkcije.js"></script>




</body>
</html>